#!/bin/sh
python ./artworks/resizer.py
python ./artworks/renamer.py

cat arttemplate.txt > art.md
printf "    " >>art.md
echo "size: $(ls ./artworks/*.png |wc -l)" >> art.md
echo "---">>art.md

if [ ! -z $1 ]; then
        git add . && git commit -m $1 && git push
fi
